### ISSUE TITLE
Integrate retractable landing gear

### ISSUE THREAD

**Issue by fnoop** [goodrobots/DevFrame#1]
eg. Tarot TL65B44

 - Looks pretty(er)
 - Makes people go 'ooh'
 - Removes legs out of way of cameras, sensors etc
 - Makes handling better (less swinging weight)

**Comment by cglusky** [comment]
I have a set on order so I can test.

Likely best method is to use a plate between them and use antivibe mounts to clamp to bottom box tubes.  

You can see how they are doing it for these...

https://www.banggood.com/HML650-Retractable-Folding-Landing-Gear-For-Tarot-650-680pro-HMF-S550-p-941639.html

**Comment by cglusky** [comment]
I have these in the shop.  I will design and test a mount but not sure it makes sense to use these in the D500 build.  Might make most sense to just add it to the wiki as an option.  They are heavy and I don't think most people will use them.

**Comment by cglusky** [comment]
For d500 which is on hold until people say they want it.  Many 450 class frames out there to use.
