### ISSUE TITLE
Raspi Zero Case

### ISSUE THREAD

**Issue by cglusky** [goodrobots/DevFrame#10]
perhaps with wifi support

**Comment by fnoop** [comment]
The official raspberry pi case is cheap and really good.  It comes with three faces including a nice one for the camera

**Comment by cglusky** [comment]
this may only be for the top/cover to integrate the wifi module i have.  not very universal so still TBD>  official case as is nice but has a curved top which can make it hard to stack stuff on top.  other COTS options though.

**Comment by cglusky** [comment]
yep.  eventually need a case system that is more stackable.  low pri for now as there are many COTS options.
