### ISSUE TITLE
D300 Basic Wiki

### ISSUE THREAD

**Issue by cglusky** [goodrobots/DevFrame#22]
Get basic BOM and enough info up to help early adopters

**Comment by fnoop** [comment]
Eager to build one of these, but can't without basic BoM and instructions!

**Comment by cglusky** [comment]
Working more on it today.

**Comment by cglusky** [comment]
https://github.com/goodrobots/DevFrame/wiki/Base-Frame-BOM

**Comment by fnoop** [comment]
Can you confirm that the imperial screw sizes convert to metric as per this guide?
https://householdquotes.co.uk/uk-screw-sizes/

**Comment by cglusky** [comment]
Yes thats a good guide. Also # 2 is 2mm and # 1 is 1.7mm. Should probably add my own chart to wiki
