### ISSUE TITLE
Update all mounts to new 15mm spaced pilot holes

### ISSUE THREAD

**Issue by cglusky** [goodrobots/DevFrame#36]
RC1 will use 1mm pilot holes vs through holes on end clamps and cross mounts.  All mounts need to be changed to support new spacing.

**Comment by cglusky** [comment]
All mounts updated to new spacing

**Comment by fnoop** [comment]
Commit?

What's the benefit/change of the new pilot holes?

**Comment by cglusky** [comment]
Just standardizing everything going forward.  Had new designs with 15mm (essentially half of the 30mm made popular by small autopilots, which is actually 30.5 but I don't worry about the .5mm since printing and drilling have bigger tolerances) so they won out.  Any old mounts you have will still work as it's just a 1mm delta.  Maybe need a light ream with a drill bit but they will still work.
