### ISSUE TITLE
Increase Size of RPi Camera Mounting Bracket

### ISSUE THREAD

**Issue by cglusky** [goodrobots/DevFrame#38]
Reports of bracket on back of mount breaking too often during hard use.  Beef up and get rid of insert for nut as it is not helpful.

**Comment by cglusky** [comment]
Done.

**Comment by fnoop** [comment]
Awesome!  I can't see a commit?

**Comment by cglusky** [comment]
Sorry, not committed yet.  Test printing and test fitting everything.  Taken me a couple days to get caught up on latest trends in sensors.  Just tracking down optical flow trends has been a pain in my ass.
