### ISSUE TITLE
Test Non-ferrous Fasteners For GPS Mount

### ISSUE THREAD

**Issue by cglusky** [goodrobots/devFrame#39]
Test brass screws with mRO GPS/compass combo to see if we have fewer compass issues

**Comment by fnoop** [comment]
What about nylon screws?

**Comment by cglusky** [comment]
Good point.  Do you have any issues sourcing?  I have some here in shop but not sure they will be right sizes.  mRobo GPS cover is designed to be screwed in and capture GPS on the mount at same time.  But you could drill it out and use nylon bolt and nut.  The mount itself is designed to be screwed into roll cage but again you could use small nylon bolt/nut combo.

**Comment by fnoop** [comment]
Yup easy peasy to get on ebay, most standard M sizes.  Also much easier to cut to size.

**Comment by cglusky** [comment]
M2 nylon on order for testing.

**Comment by cglusky** [comment]
If you use nylon they need to be M3 for required strength.
