### ISSUE TITLE
Mod RPi Cover for RPi4 w/ Fan

### ISSUE THREAD

**Issue by cglusky** [goodrobots/devFrame#43]
RPi4 needs active cooling to avoid thermal throttling.  Could use any of the new aluminum heat sinks but they are a bit heavy.

Going to try this:
https://www.amazon.com/gp/product/B07W3MJ9Y2/

Likely plugged into 3.3v based on reviews.

So RPi cover will need to support.

**Comment by fnoop** [comment]
Yes good idea to give the option, but anything flying needs much less of a heat sink, as the airflow over the chip itself should be sufficient

**Comment by cglusky** [comment]
Figured there would enough bench testing and hot days in a hover it would be worth adding.  I can keep the original cover for RPi2/3 and those who do not need fan for 4.

**Comment by cglusky** [comment]
Done in RC2
