### ISSUE TITLE
Add mount support for Nvidia Jetson Nano

### ISSUE THREAD

**Issue by fnoop** [goodrobots/devFrame#81]
Jetson Nano is a very popular board, along with Raspberry Pi.  Has a different mount size, would be nice to have it supported.

**Comment by cglusky** [comment]
Does it have mounting holes?  I don't have one and the pics I see don't show any.

I am uploading a step file from nvidia to see.  This make a board without any mounting holes thing seems to be a trend lately.  Annoying for those of us in the real world.

**Comment by cglusky** [comment]
OK.  Got them on the CAD file.

**Comment by cglusky** [comment]
86 x 58 and appear to be expecting M2.5
